version: '3.3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sincelove-chat/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URL=
    volumes:
      - .:/usr/src/node-app
    networks:
      - sincelove-chat-network

networks:
  sincelove-chat-network:
    driver: bridge
